CREATE DATABASE IF NOT EXISTS talentflow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE talentflow;
CREATE TABLE tasks(id INT AUTO_INCREMENT PRIMARY KEY, type VARCHAR(50), payload JSON, status VARCHAR(20), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE runs(id INT AUTO_INCREMENT PRIMARY KEY, task_id INT, step VARCHAR(100), status VARCHAR(20), message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE artifacts(id INT AUTO_INCREMENT PRIMARY KEY, task_id INT, kind VARCHAR(50), value VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
